"""The Hermite normal form of an integer row module.

Every subgroup `L <= Z^d` has a unique row Hermite normal form: an echelon
basis with positive pivots and every entry above a pivot reduced into
`[0, pivot)`. Two generator sets span the same subgroup exactly when their
normal forms are equal. References: C. Hermite, "Sur l'introduction des
variables continues dans la theorie des nombres", J. reine angew. Math. 41
(1851) 191-216; H. Cohen, *A Course in Computational Algebraic Number Theory*
(Springer GTM 138, 1993), section 2.4.2 (Algorithm 2.4.5); M. Newman,
*Integral Matrices* (Academic Press, 1972), chapter II.

`row_hnf` and `row_hnf_equal` were previously in
`finite_linear_algebra/integer_module.mojo`, which keeps the generic row and
Bezout helpers they are built on (the extended Euclidean algorithm) and still
re-exports both. The convention, uniqueness and what equality identifies are
stated there.
"""

from finite_exact.bigint_z import BigZ, bigz_div_exact, bigz_divmod, bigz_eq, bigz_from_i64, bigz_neg
from finite_linear_algebra.integer_module import (
    _bezout,
    _floor_div_positive,
    _row_copy,
    _row_is_zero,
    _row_linear,
    _row_neg,
    _validate_rows,
)


def row_hnf(rows: List[List[BigZ]], dimension: Int) raises -> List[List[BigZ]]:
    """Canonical nonzero row HNF for the subgroup generated by rows."""
    _validate_rows(rows, dimension)
    if dimension == 0 or len(rows) == 0:
        return List[List[BigZ]]()

    var matrix = List[List[BigZ]]()
    for i in range(len(rows)):
        matrix.append(_row_copy(rows[i]))

    var pivot_row = 0
    for column in range(dimension):
        if pivot_row >= len(matrix):
            break

        var found = -1
        for i in range(pivot_row, len(matrix)):
            if not matrix[i][column].is_zero():
                found = i
                break
        if found < 0:
            continue

        if found != pivot_row:
            var saved = _row_copy(matrix[pivot_row])
            matrix[pivot_row] = _row_copy(matrix[found])
            matrix[found] = saved^

        for i in range(pivot_row + 1, len(matrix)):
            if matrix[i][column].is_zero():
                continue

            var a = matrix[pivot_row][column].copy()
            var b = matrix[i][column].copy()
            var bezout = _bezout(a, b)
            var g = bezout.gcd.copy()

            var a_over_g = bigz_div_exact(a, g)
            var b_over_g = bigz_div_exact(b, g)
            if a_over_g.rejected or b_over_g.rejected:
                raise Error("gcd failed to divide HNF pivot entries")

            var old_pivot = _row_copy(matrix[pivot_row])
            var old_i = _row_copy(matrix[i])
            var new_pivot = _row_linear(
                bezout.x, old_pivot, bezout.y, old_i
            )
            var new_i = _row_linear(
                bigz_neg(b_over_g.quotient),
                old_pivot,
                a_over_g.quotient,
                old_i,
            )
            matrix[pivot_row] = new_pivot^
            matrix[i] = new_i^

            if not bigz_eq(matrix[pivot_row][column], g):
                raise Error("HNF Bezout step did not leave gcd at the pivot")
            if not matrix[i][column].is_zero():
                raise Error("HNF Bezout step did not clear the lower entry")

        if matrix[pivot_row][column].sign < 0:
            matrix[pivot_row] = _row_neg(matrix[pivot_row])

        var pivot = matrix[pivot_row][column].copy()
        if pivot.sign <= 0:
            raise Error("HNF pivot is not positive")

        for i in range(pivot_row):
            if matrix[i][column].is_zero():
                continue
            var q = _floor_div_positive(matrix[i][column], pivot)
            var reduced = _row_linear(
                bigz_from_i64(1),
                matrix[i],
                bigz_neg(q),
                matrix[pivot_row],
            )
            matrix[i] = reduced^
            if matrix[i][column].sign < 0:
                raise Error("HNF residue reduction left a negative entry")
            if not matrix[i][column].is_zero():
                var check = bigz_divmod(matrix[i][column], pivot)
                if check.rejected or check.quotient.sign != 0:
                    raise Error("HNF residue is not smaller than its pivot")

        pivot_row += 1

    var out = List[List[BigZ]]()
    for i in range(len(matrix)):
        if not _row_is_zero(matrix[i]):
            out.append(_row_copy(matrix[i]))
    return out^


def row_hnf_equal(
    left: List[List[BigZ]],
    right: List[List[BigZ]],
    dimension: Int,
) raises -> Bool:
    var a = row_hnf(left, dimension)
    var b = row_hnf(right, dimension)
    if len(a) != len(b):
        return False
    for i in range(len(a)):
        if len(a[i]) != len(b[i]):
            return False
        for j in range(len(a[i])):
            if not bigz_eq(a[i][j], b[i][j]):
                return False
    return True
