#!/usr/bin/env python3
"""Generate a consumer's status surfaces from one named proof-record ledger.

Specification: docs/ledger-generation-spec.md. Input is a JSON file of
named, identified proof records (section 1 of the specification). Output is:

  <tla_dir>/<Module>.tla              the TLA+ ledger for ProofArchitecture
  <tla_dir>/MC<Module>Open.{tla,cfg}  TLC model with no assumptions
  <tla_dir>/MC<Module>Imports.{tla,cfg}  TLC model assuming the imported theorems
  <tla_dir>/MC<Module><Set>.{tla,cfg}  one TLC model per declared assumption set
  <index_path>                        Markdown index of every claim
  claim_governance.toml               the [[claim]] entries, spliced between
                                      markers, when --claims names the policy

Every record is validated by the proof-records reference model and its
dependency closure is computed; a ledger with a malformed record, an
unknown dependency, or a withdrawn record that is not pending is refused
(exit 2) rather than rendered. ``--check`` compares the rendered surfaces
with the files on disk and exits 1 on any difference, so CI can enforce that
generated surfaces are current and never hand-edited.

Usage:
    python -m proof_records.generate_ledgers LEDGER.json [--out ROOT] [--claims POLICY.toml] [--check]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Relocatable: in the monorepo `proof_records/` sits at the root and the audit
# package under `audit/`; a consumer vendors `proof_records/` and
# `claim_governance/` side by side under one directory (NLAP-JT and PSC: `tools/`).
for _base in (ROOT / "audit", ROOT):
    sys.path.insert(0, str(_base))

from proof_records.records import (ACCEPTED, BOUNDED, OPEN, Closure, Edge, Kind, Record, close, outcome,  # noqa: E402
                                   validate)

FORMAT = "finite_proof_records ledger 1"
NAME = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")
WITHDRAWN_TAG = "withdrawn"
STATUS_TAG = "status:"
PROVED_KINDS = (Kind.VERIFIED, Kind.REPOSITORY)
CONDITIONAL = "conditional"
WITHDRAWN = "withdrawn"
DEFAULT_STATUS_CLASSES: Mapping[str, str] = {
    Kind.VERIFIED.value: "proved",
    Kind.REPOSITORY.value: "proved",
    CONDITIONAL: "conditional",
    Kind.IMPORTED.value: "imported",
    Kind.BOUNDED.value: "finite-domain",
    Kind.PENDING.value: "open",
    WITHDRAWN: "retired",
}
BASE_INVARIANTS = ("TypeOK", "NothingUnjustified", "NoWithdrawnDependency")
CLAIMS_BEGIN = "# BEGIN generated claims (proof_records/generate_ledgers.py); do not edit between the markers"
CLAIMS_END = "# END generated claims"
GENERATED = "Generated by proof_records/generate_ledgers.py from {source}; do not edit."
SURFACE_KEYS = ("path", "anchor", "window_lines", "section", "section_end", "expect")


class LedgerError(ValueError):
    """The ledger cannot be rendered; the message names every reason."""


@dataclass(frozen=True)
class Ledger:
    repository: str
    module: str
    records: Mapping[str, Record]
    assumption_sets: Mapping[str, tuple[str, ...]]
    status_classes: Mapping[str, str]
    status_labels: Mapping[str, str]
    tla_dir: str
    index_path: str
    source: str
    aliases: Mapping[str, tuple[str, ...]] = field(default_factory=dict)
    surfaces: Mapping[str, tuple[Mapping[str, object], ...]] = field(default_factory=dict)


@dataclass(frozen=True)
class Entry:
    name: str
    record: Record
    outcome: str
    withdrawn: bool
    status: str
    requires: tuple[str, ...]
    closure: Closure


@dataclass(frozen=True)
class Analysis:
    ledger: Ledger
    entries: tuple[Entry, ...]

    def names(self, predicate) -> tuple[str, ...]:
        return tuple(e.name for e in self.entries if predicate(e))

    @property
    def proved(self) -> tuple[str, ...]:
        return self.names(lambda e: e.outcome == ACCEPTED and e.record.kind in PROVED_KINDS)

    @property
    def imported(self) -> tuple[str, ...]:
        return self.names(lambda e: e.outcome == ACCEPTED and e.record.kind is Kind.IMPORTED)

    @property
    def bounded(self) -> tuple[str, ...]:
        return self.names(lambda e: e.outcome == BOUNDED)

    @property
    def withdrawn(self) -> tuple[str, ...]:
        return self.names(lambda e: e.withdrawn)


# --- section 1: the named ledger ---------------------------------------------------


def _kind(value) -> Kind | str:
    """The record kind, or the raw value so that validation rejects it by name."""
    return Kind(value) if value in {k.value for k in Kind} else str(value)


def record_from_json(data: Mapping) -> Record:
    return Record(
        id=str(data.get("id", "")),
        kind=_kind(data.get("kind")),
        statement=str(data.get("statement", "")),
        scope=str(data.get("scope", "")),
        depends_on=tuple(Edge(*[str(x) for x in e]) for e in data.get("depends_on", ())),
        evidence=tuple((str(k), str(v)) for k, v in data.get("evidence", ())),
        tags=frozenset(str(t) for t in data.get("tags", ())),
    )


def load_ledger(path: Path) -> Ledger:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("format") != FORMAT:
        raise LedgerError(f"unknown ledger format {data.get('format')!r}; expected {FORMAT!r}")
    records = data.get("records")
    if not isinstance(records, dict) or not records:
        raise LedgerError("ledger has no records")
    return Ledger(
        repository=str(data.get("repository", "")),
        module=str(data.get("module", "Ledger")),
        records={str(n): record_from_json(r) for n, r in records.items()},
        assumption_sets={str(k): tuple(str(x) for x in v) for k, v in data.get("assumption_sets", {}).items()},
        status_classes={**DEFAULT_STATUS_CLASSES, **{str(k): str(v) for k, v in data.get("status_classes", {}).items()}},
        status_labels={str(k): str(v) for k, v in data.get("status_labels", {}).items()},
        tla_dir=str(data.get("tla_dir", "tla")),
        index_path=str(data.get("index_path", "docs/ledger-index.md")),
        source=path.name,
        aliases={str(k): _strings(v, f"aliases[{k!r}]") for k, v in data.get("aliases", {}).items()},
        surfaces={str(k): _tables(v, f"surfaces[{k!r}]") for k, v in data.get("surfaces", {}).items()},
    )


def _strings(value, where: str) -> tuple[str, ...]:
    if not isinstance(value, list) or not all(isinstance(x, str) for x in value):
        raise LedgerError(f"{where} must be a list of strings")
    return tuple(value)


def _tables(value, where: str) -> tuple[Mapping[str, object], ...]:
    if not isinstance(value, list) or not all(isinstance(t, dict) for t in value):
        raise LedgerError(f"{where} must be a list of tables")
    return tuple(dict(t) for t in value)


def _toml(value) -> str:
    """A TOML basic string (or integer) for a passthrough value: JSON escaping
    without ASCII-only output, so non-BMP characters stay literal rather than
    becoming the surrogate escapes TOML rejects."""
    return json.dumps(value, ensure_ascii=False)


# --- section 2: analysis, fail closed --------------------------------------------


def _inside_root(path: str) -> bool:
    """A non-empty relative path with no `..` component and no absolute prefix."""
    parts = Path(path).parts
    return bool(parts) and not Path(path).is_absolute() and ".." not in parts and parts[0] not in ("/", "\\")


def output_paths(ledger: Ledger) -> tuple[str, ...]:
    """Every generated surface's path relative to the output root, the index last."""
    tla = [f"{ledger.tla_dir}/{ledger.module}.tla"] + [f"{ledger.tla_dir}/MC{ledger.module}{s}.{ext}" for s in model_suffixes(ledger) for ext in ("tla", "cfg")]
    return (*tla, ledger.index_path)


def analyse(ledger: Ledger) -> Analysis:
    errors: list[str] = []
    if not NAME.match(ledger.module):
        errors.append(f"module name {ledger.module!r} is not a TLA+ identifier")
    by_id: dict[str, str] = {}
    for name, record in ledger.records.items():
        if not NAME.match(name):
            errors.append(f"{name}: not a TLA+ identifier")
        if record.id in by_id:
            errors.append(f"{name}: identifier already used by {by_id[record.id]}")
        by_id[record.id] = name
    reserved = {"ResultSet", "RequiresDef", "ProvedDef", "ImportedDef", "BoundedDef", "WithdrawnDef", "NoAssumptions", "ImportsAssumed", "Open", "Imports"}
    for set_name, members in ledger.assumption_sets.items():
        if not NAME.match(set_name) or set_name in reserved:
            errors.append(f"assumption set {set_name!r}: invalid or reserved name")
        for member in members:
            if member not in ledger.records:
                errors.append(f"assumption set {set_name!r}: unknown record {member!r}")
    for name in ledger.assumption_sets:
        if name in ledger.records:
            errors.append(f"assumption set {name!r} collides with a record name")
    for label, value in (("tla_dir", ledger.tla_dir), ("index_path", ledger.index_path)):
        if not _inside_root(value):
            errors.append(f"{label} {value!r} must be a normalized path relative to the output root")
    if Path(ledger.index_path).as_posix() in {Path(p).as_posix() for p in output_paths(ledger)[:-1]}:
        errors.append(f"index_path {ledger.index_path!r} collides with a generated TLA+ file")
    for label, table in (("aliases", ledger.aliases), ("surfaces", ledger.surfaces)):
        for name in table:
            if name not in ledger.records:
                errors.append(f"{label} for unknown record {name!r}")
    for name, tables in ledger.surfaces.items():
        for table in tables:
            if not table.get("path"):
                errors.append(f"{name}: a passthrough surface needs a path")

    id_ledger = {r.id: r for r in ledger.records.values()}
    entries: list[Entry] = []
    for name in sorted(ledger.records):
        record = ledger.records[name]
        checked = validate(record)
        if checked.kind is Kind.REJECTED:
            errors.append(f"{name}: rejected: {checked.field('reason')}")
            continue
        requires = []
        for edge in record.depends_on:
            target = by_id.get(edge.record_id)
            if target is None:
                errors.append(f"{name}: depends on unknown record {edge.record_id[:23]}... at {edge.use_site}")
            else:
                requires.append(target)
        found = outcome(record)
        withdrawn = WITHDRAWN_TAG in record.tags
        if withdrawn and found != OPEN:
            errors.append(f"{name}: tagged withdrawn but its outcome is {found!r}; a withdrawn claim must be a pending record")
        overrides = [t[len(STATUS_TAG):] for t in sorted(record.tags) if t.startswith(STATUS_TAG)]
        if len(overrides) > 1:
            errors.append(f"{name}: more than one status override tag")
        closure = close(id_ledger, record.id)
        entries.append(Entry(name, record, found, withdrawn, _status(ledger, record, withdrawn, overrides, closure), tuple(requires), closure))
    analysis = Analysis(ledger, tuple(entries))
    withdrawn = set(analysis.withdrawn)
    requires = {e.name: set(e.requires) for e in entries}
    for set_name, members in (("ImportsAssumed", analysis.imported), *sorted(ledger.assumption_sets.items())):
        for member in members:
            if member in withdrawn:
                errors.append(f"{set_name}: {member} is withdrawn and cannot be assumed")
            elif requires.get(member, set()) & withdrawn:
                errors.append(f"{set_name}: {member} requires a withdrawn result and cannot be assumed")
    if errors:
        raise LedgerError("ledger refused:\n  " + "\n  ".join(errors))
    return analysis


def _status(ledger: Ledger, record: Record, withdrawn: bool, overrides: Sequence[str], closure: Closure) -> str:
    """Withdrawn, else the override tag, else the class of the record's kind;
    an accepted computation whose closure is incomplete is conditional."""
    if withdrawn:
        return ledger.status_classes[WITHDRAWN]
    if overrides:
        return overrides[0]
    if record.kind in PROVED_KINDS and not closure.complete:
        return ledger.status_classes[CONDITIONAL]
    return ledger.status_classes[record.kind.value]


def established(analysis: Analysis, assumed: Sequence[str]) -> frozenset[str]:
    """Least fixpoint of ProofArchitecture: the assumed results plus every
    proved result whose prerequisites are established. Withdrawn results are
    never established and block whatever requires them; `analyse` has already
    refused assumptions that are withdrawn or require a withdrawn result, so
    the fixpoint is exactly the reachable limit of the state machine."""
    proved = set(analysis.proved)
    withdrawn = set(analysis.withdrawn)
    requires = {e.name: set(e.requires) for e in analysis.entries}
    done = set(assumed)
    while True:
        ready = {r for r in proved - done if requires[r] <= done and not (requires[r] & withdrawn)}
        if not ready:
            return frozenset(done)
        done |= ready


# --- section 3: renderers -------------------------------------------------------------


def _tla_set(names: Sequence[str], indent: str = "    ") -> str:
    if not names:
        return "{}"
    return "{\n" + ",\n".join(f'{indent}"{n}"' for n in names) + "\n}"


def render_tla(analysis: Analysis) -> str:
    ledger = analysis.ledger
    lines = [f"---- MODULE {ledger.module} ----",
             f"(* {GENERATED.format(source=ledger.source)} *)",
             f"(* Repository: {ledger.repository}. *)",
             "(* Results are named proof records. Requires is one-way dependency, never a *)",
             "(* converse implication. ProvedDef holds the accepted in-repository records, *)",
             "(* ImportedDef the accepted imported theorems, BoundedDef the bounded        *)",
             "(* experiments, WithdrawnDef the withdrawn claims.                           *)",
             "EXTENDS ProofArchitecture",
             "",
             "ResultSet == " + _tla_set([e.name for e in analysis.entries]),
             "",
             "RequiresDef == [r \\in ResultSet |->"]
    first = True
    for e in analysis.entries:
        keyword = "    CASE" if first else "      []"
        first = False
        deps = "{" + ", ".join(f'"{d}"' for d in e.requires) + "}"
        lines.append(f'{keyword} r = "{e.name}" -> {deps}')
    lines[-1] += "]"
    lines += ["",
              "ProvedDef == " + _tla_set(analysis.proved),
              "",
              "ImportedDef == " + _tla_set(analysis.imported),
              "",
              "BoundedDef == " + _tla_set(analysis.bounded),
              "",
              "WithdrawnDef == " + _tla_set(analysis.withdrawn),
              "",
              "NoAssumptions == {}",
              "ImportsAssumed == ImportedDef"]
    for set_name in sorted(ledger.assumption_sets):
        lines.append(f"{set_name} == " + _tla_set(ledger.assumption_sets[set_name]))
    lines += ["", "(* Observables: one per result, asserting that it is not established. A model *)",
              "(* lists those its assumptions leave unreachable; TLC then checks the closure.  *)"]
    for e in analysis.entries:
        lines.append(f'{e.name}NotEstablished == "{e.name}" \\notin established')
    lines += ["", "===="]
    return "\n".join(lines) + "\n"


def _model(analysis: Analysis, suffix: str, assumed_def: str, assumed: Sequence[str]) -> dict[str, str]:
    """One TLC model: the base invariants, `<Name>NotEstablished` for every
    result the assumptions leave unreachable, and the liveness property that
    the reachable results are eventually all established."""
    module = analysis.ledger.module
    name = f"MC{module}{suffix}"
    reachable = established(analysis, assumed)
    ordered = [e.name for e in analysis.entries]
    unreachable = [n for n in ordered if n not in reachable]
    cfg = ["SPECIFICATION Spec", "CHECK_DEADLOCK FALSE", "",
           "CONSTANT Results   <- ResultSet", "CONSTANT Requires  <- RequiresDef", "CONSTANT Proved    <- ProvedDef",
           "CONSTANT Withdrawn <- WithdrawnDef", f"CONSTANT Assumed   <- {assumed_def}", "", "INVARIANTS"]
    cfg += [f"    {inv}" for inv in BASE_INVARIANTS] + [f"    {n}NotEstablished" for n in unreachable]
    cfg += ["", "PROPERTY", "    EventuallyReachable"]
    tla = "\n".join([f"---- MODULE {name} ----", f"(* {GENERATED.format(source=analysis.ledger.source)} *)", f"EXTENDS {module}", "",
                      "Reachable == " + _tla_set([n for n in ordered if n in reachable]),
                      "EventuallyReachable == <>(established = Reachable)", "====", ""])
    return {f"{name}.tla": tla, f"{name}.cfg": "\n".join(cfg) + "\n"}


def model_suffixes(ledger: Ledger) -> tuple[str, ...]:
    """`Open`, `Imports`, then every declared assumption set by name."""
    return ("Open", "Imports", *sorted(ledger.assumption_sets))


def render_models(analysis: Analysis) -> dict[str, str]:
    out = {**_model(analysis, "Open", "NoAssumptions", ()), **_model(analysis, "Imports", "ImportsAssumed", analysis.imported)}
    for name in sorted(analysis.ledger.assumption_sets):
        out.update(_model(analysis, name, name, analysis.ledger.assumption_sets[name]))
    return out


def render_claims(analysis: Analysis) -> str:
    ledger = analysis.ledger
    tla_path = f"{ledger.tla_dir}/{ledger.module}.tla"
    out = [CLAIMS_BEGIN, f"# {GENERATED.format(source=ledger.source)}"]
    for e in analysis.entries:
        member = ("ProvedDef", "present") if e.name in analysis.proved else ("ImportedDef", "present") if e.name in analysis.imported \
            else ("WithdrawnDef", "present") if e.withdrawn else ("ProvedDef", "absent")
        out += ["", "[[claim]]", f'name = "{e.name}"', f'status = "{e.status}"']
        if ledger.aliases.get(e.name):
            out.append("aliases = [" + ", ".join(_toml(a) for a in ledger.aliases[e.name]) + "]")
        out += ["[[claim.surfaces]]", f'path = "{tla_path}"', f"anchor = '\"{e.name}\"'", f'section = "{member[0]} == {{"',
                'section_end = "}"', f'expect = "{member[1]}"',
                "[[claim.surfaces]]", f'path = "{ledger.index_path}"', f"anchor = '| {e.name} |'", "window_lines = 0"]
        for table in ledger.surfaces.get(e.name, ()):
            out.append("[[claim.surfaces]]")
            out += [f"{k} = {_toml(table[k])}" for k in SURFACE_KEYS if k in table]
    out.append(CLAIMS_END)
    return "\n".join(out) + "\n"


def check_policy(text: str, analysis: Analysis) -> list[str]:
    """Reasons the spliced policy would fail the claim-governance checker:
    it does not load, or a claim's index label is not a synonym of its class."""
    sys.path.insert(0, str(ROOT / "audit"))
    from claim_governance.policy import PolicyError, policy_from_mapping  # noqa: E402
    try:
        policy = policy_from_mapping(tomllib.loads(text))
    except (PolicyError, tomllib.TOMLDecodeError, AttributeError, TypeError, ValueError, KeyError) as exc:
        return [f"policy: {exc!r}" if not isinstance(exc, PolicyError) else f"policy: {exc}"]
    labels = analysis.ledger.status_labels
    return [f"{e.name}: index label {labels.get(e.status, e.status)!r} is not a [status.synonyms] label of class {e.status!r}"
            for e in analysis.entries if e.status not in policy.status.classes_in(labels.get(e.status, e.status))]


def splice_claims(existing: str, fragment: str) -> str:
    """Replace the region between the markers, or append the fragment."""
    start = existing.find(CLAIMS_BEGIN)
    end = existing.find(CLAIMS_END, start) if start >= 0 else -1
    if start < 0 or end < 0:
        return existing.rstrip("\n") + ("\n\n" if existing.strip() else "") + fragment
    return existing[:start] + fragment.rstrip("\n") + existing[end + len(CLAIMS_END):]


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def render_index(analysis: Analysis) -> str:
    ledger = analysis.ledger
    lines = [f"# Claim ledger index: {ledger.repository}", "",
             f"**Status:** {GENERATED.format(source=ledger.source)} Each row's status label is the ledger class; "
             "the closure column is the proof-records dependency closure of the record (complete, or the missing links).", "",
             "| Claim | Status | Kind | Scope | Statement | Depends on | Closure |", "| --- | --- | --- | --- | --- | --- | --- |"]
    for e in analysis.entries:
        label = ledger.status_labels.get(e.status, e.status)
        deps = ", ".join(f"`{d}`" for d in e.requires) or "none"
        closure = "complete" if e.closure.complete else "incomplete: " + "; ".join(f"{_name(analysis, m.record_id)} ({m.reason})" for m in e.closure.missing_links)
        lines.append(f"| {e.name} | {_cell(label)} | {e.record.kind.value} | {_cell(e.record.scope)} | {_cell(e.record.statement)} | {deps} | {_cell(closure)} |")
    return "\n".join(lines) + "\n"


def _name(analysis: Analysis, record_id: str) -> str:
    for e in analysis.entries:
        if e.record.id == record_id:
            return e.name
    return record_id[:23] + "..."


def render_all(analysis: Analysis) -> dict[str, str]:
    """Every generated surface keyed by path relative to the consumer root, except the spliced policy."""
    tla_dir = analysis.ledger.tla_dir
    out = {f"{tla_dir}/{analysis.ledger.module}.tla": render_tla(analysis)}
    out.update({f"{tla_dir}/{k}": v for k, v in render_models(analysis).items()})
    out[analysis.ledger.index_path] = render_index(analysis)
    assert tuple(out) == output_paths(analysis.ledger)
    return out


# --- section 4: command line -------------------------------------------------------------


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("ledger", type=Path)
    parser.add_argument("--out", type=Path, default=Path("."), help="consumer repository root (default: .)")
    parser.add_argument("--claims", type=Path, default=None, help="claim_governance.toml to splice the [[claim]] entries into")
    parser.add_argument("--check", action="store_true", help="compare with the files on disk instead of writing")
    args = parser.parse_args(argv[1:])
    try:
        analysis = analyse(load_ledger(args.ledger))
    except (LedgerError, OSError, ValueError, KeyError, TypeError) as exc:
        print(str(exc))
        return 2
    outputs = {args.out / rel: text for rel, text in render_all(analysis).items()}
    if args.claims is not None:
        if any(args.claims.resolve() == p.resolve() for p in outputs):
            print(f"policy refused:\n  {args.claims} is itself a generated surface")
            return 2
        existing = args.claims.read_text(encoding="utf-8") if args.claims.exists() else ""
        outputs[args.claims] = splice_claims(existing, render_claims(analysis))
        problems = check_policy(outputs[args.claims], analysis)
        if problems:
            print("policy refused:\n  " + "\n  ".join(problems))
            return 2
    stale = [p for p, text in outputs.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
    if args.check:
        if stale:
            print("generated surfaces are stale:\n  " + "\n  ".join(str(p) for p in stale))
            return 1
        print(f"OK: {len(outputs)} generated surfaces are current.")
        return 0
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    print(f"wrote {len(outputs)} surfaces ({len(stale)} changed) for {analysis.ledger.repository or args.ledger.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
