"""A known-answer self-test, run at import, that refuses a wrong codec.

Round-three item R10, adopted from `larsbx/coop_substrate`. Its
`CoopSubstrate.SelfTest` runs before any child process starts and aborts boot
when the canonical encoder cannot reproduce its committed vectors, so a
substrate that would content-address wrongly never serves a request. This
package had the other two thirds of that discipline already: two independent
implementations of the codec (`records.py` and
`tests/proof_records/replay_vectors.mojo`) and committed byte-level vectors
both must reproduce. What it lacked was the gate. The vectors were checked when
somebody ran the suite, and `proof_records` is vendored into repositories that
never run it -- they compute record identities in CI and write them into
generated ledgers.

So the gate is at import. If `sha256` is not `sha256`, or the preimage layout
has moved, or the identifier suite has changed, nothing downstream gets to use
the result: `verify()` raises and the import fails.

Four checks, primitive first, exactly as the substrate orders its own:

1. FIPS 180-4 known answers for SHA-256, so a broken hash is named as a broken
   hash rather than as a changed record.
2. `preimage_bytes` of the pinned record reproduces the committed bytes.
3. `identity` reproduces the committed identifier.
4. `digest` reproduces the committed digest. The check calls the exported
   function rather than recomputing SHA-256 over `canonical_bytes`, so a
   `digest` that alone has moved is caught here instead of reaching a consumer
   that calls it.

`known_answers.py` is generated by `tools/make_vectors.py` from the same
reference ledger as `fixtures/vectors.json`, which answers the obvious
objection: constants produced by the code they check would be circular if they
were regenerated silently, and they are not. The committed file is the record,
`make_vectors.py --check` fails when a regeneration differs from it, and CI
runs that. A codec change therefore shows up as a diff a reader must accept,
not as a self-test that quietly agrees with itself.

`OVERRIDES` is the corruption hook, and it is the reason this is a check rather
than a decoration: a gate nothing can make fail proves nothing. Tests set it to
a wrong expectation and assert the raise; production never writes to it. The
substrate does the same thing through an application env it documents as never
set in production.

One component must read the codec before the answers describe it:
`tools/make_vectors.py`, which writes them. Holding the generator to the
answers it is about to replace would make an intended codec change
unrecoverable -- the import would fail before the tool that repairs it could
run. `REGENERATING` is that door, and it opens one way: the gate runs unless
the variable is set, the generator sets it around its own import and unsets it
again, and a package that loads with the gate skipped says so on stderr.
"""

from __future__ import annotations

import hashlib

from proof_records import known_answers as known
from proof_records.records import Record, digest, identity, preimage_bytes

#: The one supported way to load the package without the gate, for the generator
#: that writes the answers. Read once, at import; absent means the gate runs.
REGENERATING = "PROOF_RECORDS_REGENERATING"

#: Test-only corruption of the expected values, by attribute name of `known`.
#: Empty in production; `verify` reads it on every call.
OVERRIDES: dict[str, str] = {}

#: FIPS 180-4 examples: the empty string and "abc".
FIPS_KNOWN_ANSWERS = (
    (b"", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"),
    (b"abc", "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"),
)


class SelfTestError(RuntimeError):
    """The codec does not reproduce its known answers; nothing may use it."""


def expected(name: str) -> str:
    return OVERRIDES.get(name, getattr(known, name))


def pinned() -> Record:
    """The record the committed answers were taken from, rebuilt from its
    fields so that nothing but `known_answers.py` is trusted here."""
    return Record(known.RECORD_ID, known.RECORD_KIND, known.RECORD_STATEMENT, known.RECORD_SCOPE,
                  known.RECORD_DEPENDS_ON, known.RECORD_EVIDENCE, frozenset(known.RECORD_TAGS))


def problems() -> tuple[str, ...]:
    """Every check that fails, in order, primitive first."""
    found: list[str] = []
    for message, answer in FIPS_KNOWN_ANSWERS:
        if hashlib.sha256(message).hexdigest() != answer:
            found.append(f"sha256({message!r}) is not its FIPS 180-4 known answer")
    if found:
        return tuple(found)                       # a broken hash explains everything below it
    record = pinned()
    if preimage_bytes(record).hex() != expected("PREIMAGE_HEX"):
        found.append("preimage_bytes no longer produces the committed encoding")
    if identity(record) != expected("IDENTITY"):
        found.append("identity no longer produces the committed identifier")
    if digest(record) != expected("DIGEST"):
        found.append("digest no longer produces the committed digest")
    return tuple(found)


def verify() -> None:
    """Raise unless every known answer holds. Called at import of the package."""
    found = problems()
    if found:
        raise SelfTestError(
            "proof_records refuses to load: the canonical codec does not reproduce its "
            "known answers.\n  " + "\n  ".join(found) +
            "\n\nSee proof_records/self_test.py and docs/proof-records-specification.md. "
            "Regenerate with tools/make_vectors.py only after deciding the change is intended; "
            f"the generator sets {REGENERATING} around its own import so it can run against stale answers."
        )
