---- MODULE MCLedgerOpen ----
(* Generated by proof_records/generate_ledgers.py from ledger.json; do not edit. *)
EXTENDS Ledger

Reachable == {
    "AlgebraicEmbedding",
    "AlignedOverlapsAreStrongCoincidence",
    "BoundaryCoincidenceCriterion",
    "C3Locality",
    "DefectIntertwiner",
    "DefectTheorem",
    "Degree4Floor",
    "DominantCubicCapture",
    "DominantK2Source",
    "EndpointCore",
    "G1b1BoundedDiscrepancy",
    "GaloisWedgePropagation",
    "GlobalEndpointSync",
    "InterBlockCancellation",
    "LatticeLift",
    "LocalWitnessInjectivity",
    "MassBalanceK2Obstruction",
    "MeanAreaLift",
    "MidArea",
    "Mod3Sieve",
    "OrientationMonodromy",
    "OrientationSpectrum",
    "OverlapBadSCCNormalForm",
    "OverlapBoundaryZipperDichotomy",
    "OverlapFullRank",
    "ParikhIntertwiner",
    "ParitySieve",
    "PhiSemisimplicity",
    "RepoSeedUnionBridge",
    "SeedCentralizer",
    "SignatureReduction",
    "SpectralBlackBox",
    "SwapOverlapFiniteness",
    "Target1",
    "ThetaIntertwining",
    "UDForPowers",
    "UniqueDecodability",
    "W3LowGrowth",
    "WedgeBound"
}
EventuallyReachable == <>(established = Reachable)
====
