"""Reusable tooling for PSC balanced-pair experiments."""

from .bpa import (
    BoundaryHit,
    BoundaryLineage,
    State,
    Substitution,
    apply_substitution,
    apply_substitution_n,
    boundary_lineage,
    boundary_sync_hits,
    build_bpa,
    coincidence_boundaries,
    decompose_pair,
    endpoint_maps,
    inherited_boundary_positions,
    inherited_boundary_sync_hits,
    newborn_boundary_positions,
    newborn_boundary_sync_hits,
    normalize_state,
    parikh,
    recurrent_noncoincident_sccs,
    scc_is_productive,
    sync_pairs,
)

__all__ = [
    "BoundaryHit",
    "BoundaryLineage",
    "State",
    "Substitution",
    "apply_substitution",
    "apply_substitution_n",
    "boundary_lineage",
    "boundary_sync_hits",
    "build_bpa",
    "coincidence_boundaries",
    "decompose_pair",
    "endpoint_maps",
    "inherited_boundary_positions",
    "inherited_boundary_sync_hits",
    "newborn_boundary_positions",
    "newborn_boundary_sync_hits",
    "normalize_state",
    "parikh",
    "recurrent_noncoincident_sccs",
    "scc_is_productive",
    "sync_pairs",
]
