#!/usr/bin/env python3
"""Audit PSC manuscript sources for stale or overclaiming formulations.

The audit is intentionally conservative: it catches phrases that caused
version drift during the v11 -> v12.1 transition. It is not a LaTeX prover;
it is a CI guardrail against known bad claims.  Meta-text exemptions are
decided on the clause parse of ``prose_parser``, never on raw-text keywords.
"""
from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from prose_parser import HOLE, STAR, Alt, Block, Item, Opt, Rep, Seq, Token, match, parse, phrase, words

TEXT_SUFFIXES = {".tex", ".md", ".txt", ".rst"}
DEFAULT_SKIP_DIRS = {
    ".git",
    ".pytest_cache",
    "__pycache__",
    "dist",
    "build",
    ".venv",
    "venv",
}

CURRENT_SURFACE = {
    "README.md",
    "docs/proof-ladder.md",
    "docs/conjecture-ledger.md",
    "docs/boundary-synchronization.md",
    "docs/automation-protocol.md",
}


# Every accepted transpose suffix: ^T, ^\T, ^\top, bare \top, with optional TeX braces.
TRANSPOSE = r"(?:\^\{?\s*(?:T|\\T|\\top)\s*\}?|\\top)(?![A-Za-z])"
BAD_ASSIGNMENT = r"N[_ ]?C\s*=\s*M[_ ]?sigma"

# Exact documentation lines known to quote a retired claim as reported speech.
# The exemption is keyed by (root-relative path, rule, whole stripped line), so
# any edit to the line -- or the same line in another file -- is audited again.
KNOWN_META_LINES: frozenset[tuple[str, str, str]] = frozenset(
    ("docs/audit-2026-09-27.md", "psc-closed-premise", line)
    for line in (
        "The repository currently has **two different notions of “PSC is closed”** and they are not reconciled.",
        "2. **Project-management premise: closed.** Issue #151 and the latest comments on #84 say the project "
        "now *treats* general PSC as closed and has moved to Tier 2. Issues #84 and #138 were manually closed "
        "on 2026-09-26.",
        "| issue #151 | “General PSC is treated as closed for this project.” |",
        "| issue #84 | **closed manually** 2026-09-26; latest project-status comment says PSC is treated as "
        "closed and #84 becomes structural Tier 2 research |",
    )
)


def _flat(s: str) -> str:
    return " ".join(s.split())


@dataclass(frozen=True)
class Site:
    """The parsed clause holding a match, the matched constituent replaced by HOLE."""
    text: str
    block: Block
    index: int
    items: tuple[Item | object, ...]
    end: int

    @property
    def next_clause(self) -> tuple[Item, ...]:
        return self.block[self.index + 1].items if self.index + 1 < len(self.block) else ()

    @property
    def sentence_end(self) -> int:
        sentence = self.block[self.index].sentence
        return max(c.end for c in self.block if c.sentence == sentence)


def locate(text: str, blocks: tuple[Block, ...], start: int, end: int) -> Site | None:
    """The clause whose top-level items cover ``[start, end)``; None if it spans clauses."""
    for block in blocks:
        for index, clause in enumerate(block):
            hit = [k for k, it in enumerate(clause.items) if it.start < end and start < it.end]
            if not hit:
                continue
            i, j = hit[0], hit[-1] + 1
            if clause.items[i].start > start or clause.items[j - 1].end < end:
                return None
            items = (*clause.items[:i], HOLE, *clause.items[j:])
            return Site(text, block, index, items, clause.items[j - 1].end)
    return None


# Meta-text productions (see prose_parser for the clause grammar).  A match is
# exempt only when its own clause -- or, for an anaphoric retraction, the next
# clause -- is generated by one of these; nothing elsewhere on the line counts.
FRAMING_VERBS = (
    "cite claim assert state describe use treat assume say write present prove show "
    "establish frame call regard consider"
).split()
FRAMING = words(*(f"{v} {v}s {v}d {v}ed {v}ing {v.removesuffix('e')}ing" for v in FRAMING_VERBS))
NEG = Alt((words("never not forbid forbids forbidding avoid avoids avoiding"),
           lambda it: isinstance(it, Token) and it.word.endswith(("n't", "n’t"))))
ADV = lambda it: isinstance(it, Token) and it.word.endswith("ly")  # noqa: E731
ANY_WORD = lambda it: isinstance(it, Token) and bool(it.word)  # noqa: E731
COPULA = Seq((Opt(words("has have had")), words("is are was were be been")))
RETRACTED = words("false retired withdrawn refuted retracted")
P_C = Alt((words("p_c pc"), phrase("p c")))

# "Never describe ... PSC as proved", "do not cite X as proving C", "forbids describing C".
PROHIBITION = Seq((STAR, NEG, Opt(ADV), FRAMING, STAR, HOLE, STAR))
# "The premise that C is withdrawn", '"C" and is false'.
PREDICATED = Seq((STAR, HOLE, Opt(words("and")), COPULA, Opt(ADV), RETRACTED, STAR))
# 'The target is no longer "C"'.
NEGATED = Seq((STAR, COPULA, Alt((words("not"), phrase("no longer"))), HOLE, STAR))
# Next clause: "that premise is withdrawn", "This claim was refuted".
ANAPHOR = Seq((words("that this such"), Opt(words("a an")), Rep(ANY_WORD, 0, 2),
               words("premise target claim statement assertion assumption"),
               COPULA, Opt(ADV), RETRACTED, STAR))
# "No stale C ...", "The stale C must instead be ...", "is not C but ...".
STALE = Seq((STAR, Alt((words("stale old retired wrong incorrect not"), phrase("instead of"),
                        words("replace replaces replaced"))), Opt(words("the a an")), HOLE, STAR))
PARIKH = Seq((STAR, P_C, HOLE, P_C, STAR))
REPLACEMENT = re.compile(BAD_ASSIGNMENT + r"\s*" + TRANSPOSE, re.IGNORECASE)


def _is_parikh_intertwiner(site: Site) -> bool:
    return match(PARIKH, site.items)


def _is_stale_quote(site: Site) -> bool:
    """Marked stale in its own clause, with the transposed form later in its sentence."""
    return match(STALE, site.items) and bool(REPLACEMENT.search(site.text, site.end, site.sentence_end))


def _is_retracted(site: Site) -> bool:
    return (
        any(match(p, site.items) for p in (PROHIBITION, PREDICATED, NEGATED))
        or match(ANAPHOR, site.next_clause)
    )


@dataclass(frozen=True)
class Rule:
    name: str
    pattern: re.Pattern[str]
    message: str
    exemptions: tuple[Callable[[Site], bool], ...] = ()


RULES: tuple[Rule, ...] = (
    Rule(
        name="synthetic-countermodel-transpose",
        pattern=re.compile(BAD_ASSIGNMENT + rf"(?!\s*{TRANSPOSE})", re.IGNORECASE),
        message="Synthetic countermodel must be N_C = M_sigma^T, P = I; not N_C = M_sigma.",
        exemptions=(_is_parikh_intertwiner, _is_stale_quote),
    ),
    Rule(
        name="old-cycle-exclusion-target",
        pattern=re.compile(r"no recurrent noncoincident cycle", re.IGNORECASE),
        message="Cycle-exclusion is a retired false target; use SCC Producer / nonsynchronizing trap framing.",
        exemptions=(_is_retracted,),
    ),
    Rule(
        name="future-replacement-overclaim",
        pattern=re.compile(r"self-contained replacement is in preparation", re.IGNORECASE),
        message="Do not promise a self-contained replacement; state the precise open conjecture instead.",
    ),
    Rule(
        name="unconditional-main-theorem",
        pattern=re.compile(
            r"Then\s+(?:the\s+)?associated\s+tiling\s+dynamical\s+system\s+has\s+pure\s+discrete\s+spectrum(?![^.]{0,120}\bconditional)",
            re.IGNORECASE | re.DOTALL,
        ),
        message="Main PDS claim must be explicitly conditional unless SCC Producer is proved.",
    ),
    Rule(
        name="psc-closed-premise",
        pattern=re.compile(
            r"(?i:\b(?:PSC|Pisot\s+Substitution\s+Conjecture)\b(?:\s+[\w-]+){0,2}?"
            r"\s+(?:is|as|was|has\s+been)\s+(?:(?:now|treated\s+as|considered)\s+)?"
            r"(?:closed|proved|proven|settled|resolved)\b)"
            r"|(?<![\w/-])post-PSC(?![\w-])"
        ),
        message="PSC is open (one open premise, OP_seed / #84); do not state or premise it as proved or closed.",
        exemptions=(_is_retracted,),
    ),
    Rule(
        name="loose-subblock-language",
        pattern=re.compile(r"contains\s+M[_ ]?sigma\s+as\s+an\s+invariant\s+sub-?block", re.IGNORECASE),
        message="Use 'acts on an invariant subspace as a similar copy of M_sigma' instead of loose sub-block language.",
    ),
)


def iter_text_files(root: Path, strict_current: bool = False):
    if strict_current:
        base = root.resolve()
        for rel in sorted(CURRENT_SURFACE):
            path = base / rel
            if path.exists():
                yield path
        return

    for path in root.rglob("*"):
        if path.is_dir():
            continue
        if any(part in DEFAULT_SKIP_DIRS for part in path.parts):
            continue
        if path.suffix.lower() in TEXT_SUFFIXES:
            yield path


def _is_known_meta_line(rel: str, rule: Rule, text: str, m: re.Match[str]) -> bool:
    line_start = text.rfind("\n", 0, m.start()) + 1
    line_end = text.find("\n", m.end())
    line = text[line_start:len(text) if line_end == -1 else line_end].strip()
    return (rel, rule.name, line) in KNOWN_META_LINES


def audit_file(path: Path, root: Path | None = None) -> list[str]:
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return []
    rel = (path.resolve().relative_to(root.resolve()) if root else path).as_posix()
    blocks = parse(text)

    def exempt(rule: Rule, m: re.Match[str]) -> bool:
        site = locate(text, blocks, m.start(), m.end())
        return bool(site and any(e(site) for e in rule.exemptions)) or _is_known_meta_line(rel, rule, text, m)

    return [
        f"{path}:{text.count(chr(10), 0, m.start()) + 1}: {rule.name}: {rule.message} "
        f"[matched: {_flat(m.group(0))!r}]"
        for rule in RULES
        for m in rule.pattern.finditer(text)
        if not exempt(rule, m)
    ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="repository root to audit")
    parser.add_argument(
        "--strict-current",
        action="store_true",
        help="audit only the canonical current manuscript/research surface, not archives",
    )
    args = parser.parse_args(argv)

    root = args.root.resolve()
    failures: list[str] = []
    for path in iter_text_files(root, strict_current=args.strict_current):
        failures.extend(audit_file(path, root))

    if failures:
        print("PSC manuscript/source audit failed:", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1
    print("PSC manuscript/source audit passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
