#!/usr/bin/env python3
"""Render the mathematical-object catalogue from its single TOML source."""
from __future__ import annotations

import argparse
from pathlib import Path
import sys
import tomllib

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "catalogues" / "mathematical_objects.toml"
OUTPUT = ROOT / "docs" / "mathematical-object-catalogue.md"


def _link(path: str) -> str:
    return f"[`{path}`](../{path})"


def render() -> str:
    data = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    taxonomies = data["taxonomy"]
    objects = data["object"]
    tax_by_id = {item["id"]: item for item in taxonomies}
    object_by_id = {item["id"]: item for item in objects}
    if len(tax_by_id) != len(taxonomies) or len(object_by_id) != len(objects):
        raise ValueError("catalogue IDs must be unique")
    for item in objects:
        if item["taxonomy"] not in tax_by_id:
            raise ValueError(f"{item['id']}: unknown taxonomy {item['taxonomy']}")
        unknown = set(item.get("related", ())) - object_by_id.keys()
        if unknown:
            raise ValueError(f"{item['id']}: unknown related objects {sorted(unknown)}")

    lines = [
        "# Mathematical-object catalogue",
        "",
        "<!-- Generated by scripts/make_math_catalogue.py; edit catalogues/mathematical_objects.toml. -->",
        "",
        data["description"],
        "",
        "This is the human-browsable view of the canonical structured registry in",
        "[`catalogues/mathematical_objects.toml`](../catalogues/mathematical_objects.toml).",
        "Implementation links state authority explicitly: **Mojo is canonical**; a Python",
        "link names an independent oracle or diagnostic, never a second source of truth.",
        "",
        "## Taxonomy index",
        "",
        "| Taxonomy | Meaning | Objects |",
        "| --- | --- | --- |",
    ]
    for tax in taxonomies:
        members = [obj for obj in objects if obj["taxonomy"] == tax["id"]]
        links = ", ".join(f"[{obj['name']}](#{obj['id']})" for obj in members)
        lines.append(f"| {tax['name']} | {tax['description']} | {links} |")

    lines += [
        "",
        "## Object index",
        "",
        "| Object | Class | Status | Canonical implementation | Oracle / diagnostic |",
        "| --- | --- | --- | --- | --- |",
    ]
    for item in objects:
        tax = tax_by_id[item["taxonomy"]]["name"]
        lines.append(
            f"| [{item['name']}](#{item['id']}) | {tax} | `{item['status']}` | "
            f"{_link(item['canonical'])} | {_link(item['oracle'])} |"
        )

    lines += ["", "## Definitions", ""]
    for item in objects:
        related = ", ".join(
            f"[{object_by_id[r]['name']}](#{r})" for r in item.get("related", ())
        ) or "None"
        lines += [
            f"<a id=\"{item['id']}\"></a>",
            f"### {item['name']}",
            "",
            f"- **Catalogue ID:** `{item['id']}`",
            f"- **Taxonomy:** {tax_by_id[item['taxonomy']]['name']}",
            f"- **Status:** `{item['status']}`",
            f"- **Definition:** {item['definition']}",
            f"- **Scope boundary:** {item['scope']}",
            f"- **Canonical Mojo:** {_link(item['canonical'])}",
            f"- **Independent oracle / diagnostic:** {_link(item['oracle'])}",
            f"- **Related objects:** {related}",
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated Markdown is stale")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"stale generated catalogue: run {Path(__file__).name}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
