"""Deterministic clause parser for Markdown/TeX prose.

The parser is total (every input parses) and has no statistical component, so
an audit decision is a function of the text alone.  Grammar, over the tokens
produced by ``lex`` (words compared case-insensitively)::

    document   = block { block } ;
    block      = sentence { sentence } ;
    sentence   = clause { CLAUSE_SEP clause } [ TERMINATOR ] ;
    clause     = { item } ;
    item       = token | quote ;
    quote      = OPEN { token | quote } CLOSE ;      (* one opaque constituent *)

    BLOCK_SEP  = blank line | newline before a list item, table row or heading ;
    TERMINATOR = "." | "!" | "?" , followed by whitespace or end of text ;
    CLAUSE_SEP = ";" | "|" | ":" + whitespace
               | "," SUBORDINATOR | "," PRONOUN | "," "and" ( PRONOUN | DETERMINER ) ;

Separators and terminators inside a quote are quote content.  An unclosed
quote is not a constituent: its opening mark is read as an ordinary symbol.

``match`` decides whether a clause, with one constituent replaced by the
``HOLE`` sentinel, is generated by a production built from ``Seq``/``Alt``/
``Opt``/``Rep``, word sets, predicates and ``STAR`` (any items).
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Callable, Union

_TOKEN = re.compile(
    r"(?P<blank>\n[ \t]*\n\s*)"
    r"|(?P<item>\n(?=[ \t]*(?:[-*+]|\d+\.|\#+|\|)\s))"
    r"|(?P<open>``|“)"
    r"|(?P<close>''|”)"
    r"|(?P<dquote>\")"
    r"|(?P<code>`[^`\n]*`)"
    r"|(?P<tex>\\(?:[A-Za-z]+|[^A-Za-z]))"
    r"|(?P<word>\w(?:[\w'’/.-]*\w)?)"
    r"|(?P<punct>[.;:,!?|])"
    r"|(?P<sym>\S)"
)
# Markup that carries no syntax: emphasis, math delimiters, TeX spacing.
_NOISE = frozenset("*_~$") | {"\\,", "\\;", "\\:", "\\!", "\\ ", "\\quad", "\\qquad"}

SUBORDINATORS = frozenset(
    "which while whereas although because since hence thus so but yet".split()
)
PRONOUNS = frozenset("we i you they it this that these those he she one".split())
DETERMINERS = frozenset("the a an this that these those our its their".split())


@dataclass(frozen=True)
class Token:
    kind: str
    text: str
    start: int
    end: int

    @property
    def word(self) -> str:
        return self.text.lower() if self.kind == "word" else ""


@dataclass(frozen=True)
class Quote:
    items: tuple[Item, ...]
    start: int
    end: int


Item = Union[Token, Quote]


@dataclass(frozen=True)
class Clause:
    items: tuple[Item, ...]
    sentence: int

    @property
    def start(self) -> int:
        return self.items[0].start

    @property
    def end(self) -> int:
        return self.items[-1].end


Block = tuple[Clause, ...]


def lex(text: str) -> tuple[Token, ...]:
    return tuple(
        Token(m.lastgroup or "sym", m.group(), m.start(), m.end())
        for m in _TOKEN.finditer(text)
        if m.group() not in _NOISE
    )


def _terminates(tok: Token, text: str) -> bool:
    return tok.text in ".!?" and (tok.end == len(text) or text[tok.end].isspace())


def _separates(toks: tuple[Token, ...], k: int, text: str) -> bool:
    tok, nxt = toks[k], toks[k + 1:k + 3]
    if tok.text in ";|":
        return True
    if tok.text == ":":
        return tok.end == len(text) or text[tok.end].isspace()
    if tok.text != "," or not nxt:
        return False
    w = nxt[0].word
    return (
        w in SUBORDINATORS
        or w in PRONOUNS
        or (w == "and" and len(nxt) > 1 and (nxt[1].word in PRONOUNS or nxt[1].word in DETERMINERS))
    )


def _pair_quotes(toks: tuple[Token, ...]) -> tuple[Token, ...]:
    """Resolve quote marks: paired ones become ``open``/``close``, the rest plain symbols."""
    stack: list[int] = []
    role: dict[int, str] = {}
    for k, tok in enumerate(toks):
        top = toks[stack[-1]].kind if stack else None
        if (tok.kind == "close" and top == "open") or (tok.kind == "dquote" and top == "dquote"):
            role |= {stack.pop(): "open", k: "close"}
        elif tok.kind in ("open", "dquote"):
            stack.append(k)
    return tuple(
        Token(role.get(k, "sym"), t.text, t.start, t.end) if t.kind in ("open", "close", "dquote") else t
        for k, t in enumerate(toks)
    )


def _group_quotes(toks: list[Token]) -> tuple[Item, ...]:
    """Nest the paired quote marks of one clause into Quote items."""
    stack: list[tuple[Token, list[Item]]] = []
    out: list[Item] = []
    for tok in toks:
        if tok.kind == "open":
            stack.append((tok, []))
        elif tok.kind == "close":
            opener, inner = stack.pop()
            (stack[-1][1] if stack else out).append(Quote(tuple(inner), opener.start, tok.end))
        else:
            (stack[-1][1] if stack else out).append(tok)
    return tuple(out)


def _blocks(toks: tuple[Token, ...]) -> tuple[tuple[Token, ...], ...]:
    runs: list[list[Token]] = [[]]
    for tok in toks:
        if tok.kind in ("blank", "item"):
            runs.append([])
        else:
            runs[-1].append(tok)
    return tuple(_pair_quotes(tuple(run)) for run in runs if run)


def _clauses(toks: tuple[Token, ...], text: str) -> Block:
    clauses: list[Clause] = []
    current: list[Token] = []
    sentence = depth = 0

    def close() -> None:
        if current:
            clauses.append(Clause(_group_quotes(current), sentence))
            current.clear()

    for k, tok in enumerate(toks):
        if tok.kind in ("open", "close"):
            depth += 1 if tok.kind == "open" else -1
        elif depth == 0 and tok.kind == "punct" and _terminates(tok, text):
            close()
            sentence += 1
            continue
        elif depth == 0 and tok.kind == "punct" and _separates(toks, k, text):
            close()
            continue
        current.append(tok)
    close()
    return tuple(clauses)


def parse(text: str) -> tuple[Block, ...]:
    return tuple(_clauses(run, text) for run in _blocks(lex(text)))


# --- productions -----------------------------------------------------------

HOLE = object()  # the constituent under audit
STAR = object()  # any (possibly empty) run of items

Elem = Union[frozenset, Callable[[Item], bool], object, "Seq", "Alt", "Opt", "Rep"]


@dataclass(frozen=True)
class Seq:
    elems: tuple[Elem, ...]


@dataclass(frozen=True)
class Alt:
    options: tuple[Elem, ...]


@dataclass(frozen=True)
class Opt:
    elem: Elem


@dataclass(frozen=True)
class Rep:
    elem: Elem
    lo: int
    hi: int


def words(*ws: str) -> frozenset[str]:
    return frozenset(w for group in ws for w in group.split())


def phrase(text: str) -> Seq:
    return Seq(tuple(frozenset([w]) for w in text.split()))


def _step(elem: Elem, items: tuple, i: int):
    """Yield every index reachable after matching ``elem`` at ``items[i:]``."""
    if elem is STAR:
        yield from range(i, len(items) + 1)
    elif elem is HOLE:
        if i < len(items) and items[i] is HOLE:
            yield i + 1
    elif isinstance(elem, Seq):
        yield from _seq(elem.elems, items, i)
    elif isinstance(elem, Alt):
        for option in elem.options:
            yield from _step(option, items, i)
    elif isinstance(elem, Opt):
        yield i
        yield from _step(elem.elem, items, i)
    elif isinstance(elem, Rep):
        frontier = {i}
        for n in range(elem.hi + 1):
            if n >= elem.lo:
                yield from frontier
            frontier = {j for f in frontier for j in _step(elem.elem, items, f)}
    elif i < len(items) and items[i] is not HOLE:
        item = items[i]
        word = item.word if isinstance(item, Token) else ""
        if (elem(item) if callable(elem) else word in elem):
            yield i + 1


def _seq(elems: tuple[Elem, ...], items: tuple, i: int):
    if not elems:
        yield i
        return
    for j in set(_step(elems[0], items, i)):
        yield from _seq(elems[1:], items, j)


def match(production: Elem, items: tuple) -> bool:
    """``items`` is exactly generated by ``production``."""
    return len(items) in set(_step(production, items, 0))
