---- MODULE Ledger ----
(* Generated by proof_records/generate_ledgers.py from ledger.json; do not edit. *)
(* Repository: larsbx/pisot-substitution-conjecture-research. *)
(* Results are named proof records. Requires is one-way dependency, never a *)
(* converse implication. ProvedDef holds the accepted in-repository records, *)
(* ImportedDef the accepted imported theorems, BoundedDef the bounded        *)
(* experiments, WithdrawnDef the withdrawn claims.                           *)
EXTENDS ProofArchitecture

ResultSet == {
    "AlgebraicEmbedding",
    "AlignedOverlapsAreStrongCoincidence",
    "AllStatesProductiveViaOverlaps",
    "BoundaryCoincidenceCriterion",
    "C2",
    "C3Local",
    "C3Locality",
    "C4",
    "CoincidenceDensityOne",
    "ConcentrationAuxB",
    "DefectIntertwiner",
    "DefectTheorem",
    "Degree4Floor",
    "DensityToPDSBridge",
    "DominantCubicCapture",
    "DominantK2Source",
    "EndpointCore",
    "G1",
    "G1FromRenewal",
    "G1b1BoundedDiscrepancy",
    "G1b2RenewalFiniteness",
    "GaloisWedgePropagation",
    "GlobalEndpointSync",
    "InterBlockCancellation",
    "LatticeLift",
    "LoadBearingSCC",
    "LocalWitnessInjectivity",
    "MassBalanceK2Obstruction",
    "MeanAreaLift",
    "MidArea",
    "Mod3Sieve",
    "OrientationMonodromy",
    "OrientationSpectrum",
    "OverlapBadSCCNormalForm",
    "OverlapBoundaryZipperDichotomy",
    "OverlapFullRank",
    "OverlapProductivity",
    "PDS",
    "PDSImpliesRepoG1",
    "PDSOverlapRoute",
    "PDSSpectralRoute",
    "ParikhIntertwiner",
    "ParitySieve",
    "PhiSemisimplicity",
    "RepoSeedUnionBridge",
    "SCCProducer",
    "SeedCentralizer",
    "SignatureReduction",
    "SinkSCCReduction",
    "SpanRichProductivity",
    "SpectralBlackBox",
    "SpectralSCCProducer",
    "StandardBPAEquivalence",
    "SwapOverlapFiniteness",
    "Target1",
    "ThetaIntertwining",
    "UDForPowers",
    "UniqueDecodability",
    "V5Thm51",
    "W3LowGrowth",
    "WedgeBound"
}

RequiresDef == [r \in ResultSet |->
    CASE r = "AlgebraicEmbedding" -> {"UniqueDecodability"}
      [] r = "AlignedOverlapsAreStrongCoincidence" -> {}
      [] r = "AllStatesProductiveViaOverlaps" -> {"OverlapProductivity", "SwapOverlapFiniteness"}
      [] r = "BoundaryCoincidenceCriterion" -> {}
      [] r = "C2" -> {"C3Local"}
      [] r = "C3Local" -> {"C4", "C3Locality"}
      [] r = "C3Locality" -> {}
      [] r = "C4" -> {}
      [] r = "CoincidenceDensityOne" -> {"OverlapProductivity", "SwapOverlapFiniteness"}
      [] r = "ConcentrationAuxB" -> {"G1", "SinkSCCReduction"}
      [] r = "DefectIntertwiner" -> {"OrientationMonodromy"}
      [] r = "DefectTheorem" -> {}
      [] r = "Degree4Floor" -> {"DefectIntertwiner"}
      [] r = "DensityToPDSBridge" -> {}
      [] r = "DominantCubicCapture" -> {"Target1"}
      [] r = "DominantK2Source" -> {}
      [] r = "EndpointCore" -> {}
      [] r = "G1" -> {"G1FromRenewal"}
      [] r = "G1FromRenewal" -> {"G1b1BoundedDiscrepancy", "G1b2RenewalFiniteness"}
      [] r = "G1b1BoundedDiscrepancy" -> {}
      [] r = "G1b2RenewalFiniteness" -> {"G1b1BoundedDiscrepancy"}
      [] r = "GaloisWedgePropagation" -> {}
      [] r = "GlobalEndpointSync" -> {"EndpointCore"}
      [] r = "InterBlockCancellation" -> {}
      [] r = "LatticeLift" -> {"MeanAreaLift"}
      [] r = "LoadBearingSCC" -> {"G1", "DominantK2Source", "InterBlockCancellation"}
      [] r = "LocalWitnessInjectivity" -> {}
      [] r = "MassBalanceK2Obstruction" -> {}
      [] r = "MeanAreaLift" -> {"MidArea", "ParikhIntertwiner"}
      [] r = "MidArea" -> {}
      [] r = "Mod3Sieve" -> {"DefectIntertwiner"}
      [] r = "OrientationMonodromy" -> {}
      [] r = "OrientationSpectrum" -> {"OrientationMonodromy", "ParikhIntertwiner"}
      [] r = "OverlapBadSCCNormalForm" -> {"SwapOverlapFiniteness", "OverlapFullRank"}
      [] r = "OverlapBoundaryZipperDichotomy" -> {"OverlapBadSCCNormalForm", "AlignedOverlapsAreStrongCoincidence", "BoundaryCoincidenceCriterion"}
      [] r = "OverlapFullRank" -> {}
      [] r = "OverlapProductivity" -> {}
      [] r = "PDS" -> {"G1", "SCCProducer"}
      [] r = "PDSImpliesRepoG1" -> {"StandardBPAEquivalence", "RepoSeedUnionBridge"}
      [] r = "PDSOverlapRoute" -> {"CoincidenceDensityOne", "DensityToPDSBridge"}
      [] r = "PDSSpectralRoute" -> {"G1", "SpectralSCCProducer"}
      [] r = "ParikhIntertwiner" -> {}
      [] r = "ParitySieve" -> {"DefectIntertwiner"}
      [] r = "PhiSemisimplicity" -> {}
      [] r = "RepoSeedUnionBridge" -> {}
      [] r = "SCCProducer" -> {"G1", "SinkSCCReduction", "C2"}
      [] r = "SeedCentralizer" -> {"ThetaIntertwining", "PhiSemisimplicity"}
      [] r = "SignatureReduction" -> {"EndpointCore"}
      [] r = "SinkSCCReduction" -> {"G1"}
      [] r = "SpanRichProductivity" -> {"ConcentrationAuxB", "GaloisWedgePropagation"}
      [] r = "SpectralBlackBox" -> {"Target1", "DominantCubicCapture"}
      [] r = "SpectralSCCProducer" -> {"G1", "SinkSCCReduction", "SpanRichProductivity"}
      [] r = "StandardBPAEquivalence" -> {}
      [] r = "SwapOverlapFiniteness" -> {"G1b1BoundedDiscrepancy"}
      [] r = "Target1" -> {"SeedCentralizer"}
      [] r = "ThetaIntertwining" -> {}
      [] r = "UDForPowers" -> {"UniqueDecodability"}
      [] r = "UniqueDecodability" -> {"DefectTheorem"}
      [] r = "V5Thm51" -> {}
      [] r = "W3LowGrowth" -> {"DefectIntertwiner", "PhiSemisimplicity"}
      [] r = "WedgeBound" -> {"AlgebraicEmbedding", "MassBalanceK2Obstruction"}]

ProvedDef == {
    "AlgebraicEmbedding",
    "AlignedOverlapsAreStrongCoincidence",
    "AllStatesProductiveViaOverlaps",
    "BoundaryCoincidenceCriterion",
    "C2",
    "C3Local",
    "C3Locality",
    "CoincidenceDensityOne",
    "DefectIntertwiner",
    "DefectTheorem",
    "Degree4Floor",
    "DominantCubicCapture",
    "DominantK2Source",
    "EndpointCore",
    "G1",
    "G1FromRenewal",
    "G1b1BoundedDiscrepancy",
    "GaloisWedgePropagation",
    "GlobalEndpointSync",
    "InterBlockCancellation",
    "LatticeLift",
    "LoadBearingSCC",
    "LocalWitnessInjectivity",
    "MassBalanceK2Obstruction",
    "MeanAreaLift",
    "MidArea",
    "Mod3Sieve",
    "OrientationMonodromy",
    "OrientationSpectrum",
    "OverlapBadSCCNormalForm",
    "OverlapBoundaryZipperDichotomy",
    "OverlapFullRank",
    "PDS",
    "PDSOverlapRoute",
    "PDSSpectralRoute",
    "ParikhIntertwiner",
    "ParitySieve",
    "PhiSemisimplicity",
    "RepoSeedUnionBridge",
    "SCCProducer",
    "SeedCentralizer",
    "SignatureReduction",
    "SinkSCCReduction",
    "SpectralBlackBox",
    "SwapOverlapFiniteness",
    "Target1",
    "ThetaIntertwining",
    "UDForPowers",
    "UniqueDecodability",
    "W3LowGrowth",
    "WedgeBound"
}

ImportedDef == {
    "DensityToPDSBridge",
    "StandardBPAEquivalence"
}

BoundedDef == {}

WithdrawnDef == {
    "V5Thm51"
}

NoAssumptions == {}
ImportsAssumed == ImportedDef
G1AndC4 == {
    "G1",
    "C4"
}
G1AndProducer == {
    "G1",
    "SCCProducer"
}
G1Only == {
    "G1"
}
OverlapGateAssumed == {
    "OverlapProductivity",
    "DensityToPDSBridge"
}
RenewalGateAssumed == {
    "G1b1BoundedDiscrepancy",
    "G1b2RenewalFiniteness"
}
SpectralGateAssumed == {
    "G1",
    "ConcentrationAuxB",
    "SpanRichProductivity",
    "SpectralSCCProducer"
}

(* Observables: one per result, asserting that it is not established. A model *)
(* lists those its assumptions leave unreachable; TLC then checks the closure.  *)
AlgebraicEmbeddingNotEstablished == "AlgebraicEmbedding" \notin established
AlignedOverlapsAreStrongCoincidenceNotEstablished == "AlignedOverlapsAreStrongCoincidence" \notin established
AllStatesProductiveViaOverlapsNotEstablished == "AllStatesProductiveViaOverlaps" \notin established
BoundaryCoincidenceCriterionNotEstablished == "BoundaryCoincidenceCriterion" \notin established
C2NotEstablished == "C2" \notin established
C3LocalNotEstablished == "C3Local" \notin established
C3LocalityNotEstablished == "C3Locality" \notin established
C4NotEstablished == "C4" \notin established
CoincidenceDensityOneNotEstablished == "CoincidenceDensityOne" \notin established
ConcentrationAuxBNotEstablished == "ConcentrationAuxB" \notin established
DefectIntertwinerNotEstablished == "DefectIntertwiner" \notin established
DefectTheoremNotEstablished == "DefectTheorem" \notin established
Degree4FloorNotEstablished == "Degree4Floor" \notin established
DensityToPDSBridgeNotEstablished == "DensityToPDSBridge" \notin established
DominantCubicCaptureNotEstablished == "DominantCubicCapture" \notin established
DominantK2SourceNotEstablished == "DominantK2Source" \notin established
EndpointCoreNotEstablished == "EndpointCore" \notin established
G1NotEstablished == "G1" \notin established
G1FromRenewalNotEstablished == "G1FromRenewal" \notin established
G1b1BoundedDiscrepancyNotEstablished == "G1b1BoundedDiscrepancy" \notin established
G1b2RenewalFinitenessNotEstablished == "G1b2RenewalFiniteness" \notin established
GaloisWedgePropagationNotEstablished == "GaloisWedgePropagation" \notin established
GlobalEndpointSyncNotEstablished == "GlobalEndpointSync" \notin established
InterBlockCancellationNotEstablished == "InterBlockCancellation" \notin established
LatticeLiftNotEstablished == "LatticeLift" \notin established
LoadBearingSCCNotEstablished == "LoadBearingSCC" \notin established
LocalWitnessInjectivityNotEstablished == "LocalWitnessInjectivity" \notin established
MassBalanceK2ObstructionNotEstablished == "MassBalanceK2Obstruction" \notin established
MeanAreaLiftNotEstablished == "MeanAreaLift" \notin established
MidAreaNotEstablished == "MidArea" \notin established
Mod3SieveNotEstablished == "Mod3Sieve" \notin established
OrientationMonodromyNotEstablished == "OrientationMonodromy" \notin established
OrientationSpectrumNotEstablished == "OrientationSpectrum" \notin established
OverlapBadSCCNormalFormNotEstablished == "OverlapBadSCCNormalForm" \notin established
OverlapBoundaryZipperDichotomyNotEstablished == "OverlapBoundaryZipperDichotomy" \notin established
OverlapFullRankNotEstablished == "OverlapFullRank" \notin established
OverlapProductivityNotEstablished == "OverlapProductivity" \notin established
PDSNotEstablished == "PDS" \notin established
PDSImpliesRepoG1NotEstablished == "PDSImpliesRepoG1" \notin established
PDSOverlapRouteNotEstablished == "PDSOverlapRoute" \notin established
PDSSpectralRouteNotEstablished == "PDSSpectralRoute" \notin established
ParikhIntertwinerNotEstablished == "ParikhIntertwiner" \notin established
ParitySieveNotEstablished == "ParitySieve" \notin established
PhiSemisimplicityNotEstablished == "PhiSemisimplicity" \notin established
RepoSeedUnionBridgeNotEstablished == "RepoSeedUnionBridge" \notin established
SCCProducerNotEstablished == "SCCProducer" \notin established
SeedCentralizerNotEstablished == "SeedCentralizer" \notin established
SignatureReductionNotEstablished == "SignatureReduction" \notin established
SinkSCCReductionNotEstablished == "SinkSCCReduction" \notin established
SpanRichProductivityNotEstablished == "SpanRichProductivity" \notin established
SpectralBlackBoxNotEstablished == "SpectralBlackBox" \notin established
SpectralSCCProducerNotEstablished == "SpectralSCCProducer" \notin established
StandardBPAEquivalenceNotEstablished == "StandardBPAEquivalence" \notin established
SwapOverlapFinitenessNotEstablished == "SwapOverlapFiniteness" \notin established
Target1NotEstablished == "Target1" \notin established
ThetaIntertwiningNotEstablished == "ThetaIntertwining" \notin established
UDForPowersNotEstablished == "UDForPowers" \notin established
UniqueDecodabilityNotEstablished == "UniqueDecodability" \notin established
V5Thm51NotEstablished == "V5Thm51" \notin established
W3LowGrowthNotEstablished == "W3LowGrowth" \notin established
WedgeBoundNotEstablished == "WedgeBound" \notin established

====
