"""Finite exact quotient diagnostics for regular joint-local collision loops.

This module does not assert renewal finiteness. It takes the bounded
`JointLocalType` collision classes from the G1b-2 census, retains the full exact
renewal address for each certified observation, and quotients only by connected
components generated by observed one-level synchronous address extensions.

Two exact symbolic relations are available. The first uses one nominated digit
pair on both sides, preserving the original `(1,2)` regression. The second
admits any one-level extension in which top and bottom each insert one digit
pair at the same ancestry position; the two inserted side-digits need not
agree.

After forming the symbolic quotient, an optional finite arithmetic diagnostic
asks how many residual pairs still agree on the exact level-scaled certificate
`M^d delta` modulo a supplied integer. For the determinant-2 regression we probe
powers of two. This is evidence about a possible profinite coordinate only; the
residue is not assumed to be a recurrence invariant and is not promoted to a
state quotient or theorem.

The quotient is deliberately empirical and corpus-relative. It does not delete
arbitrary digits from an address and does not invent a global normal form. Only
actually observed certified edges generate identifications. Pairs in different
connected components remain explicit residual counterexamples.
"""

from psc.joint_local_census import (
    ObservationKey,
    address_is_one_loop_extension,
    digit_pair_insertion_at,
    zero_return_cuts,
)
from psc.joint_local_type import (
    JointLocalType,
    joint_local_type_from_certified,
    same_joint_local_type,
)
from psc.renewal_address import (
    RelativeRenewalAddress,
    build_renewal_address_tables,
    build_renewal_pair_census_state,
    certified_renewal_cut_from_state,
    same_relative_address,
)
from psc.words import Pair


struct AddressedJointLocalSample(Copyable, Movable):
    """One certified bounded projection together with its exact full address."""

    var specimen_id: Int
    var depth: Int
    var cut: Int
    var projection: JointLocalType
    var address: RelativeRenewalAddress

    def __init__(
        out self,
        specimen_id: Int,
        depth: Int,
        cut: Int,
        projection: JointLocalType,
        address: RelativeRenewalAddress,
    ):
        self.specimen_id = specimen_id
        self.depth = depth
        self.cut = cut
        self.projection = projection.copy()
        self.address = address.copy()


struct LoopQuotientAudit(Copyable, Movable):
    """Collision counts after symbolic quotient and optional residue refinement."""

    var sample_count: Int
    var projection_collision_pair_count: Int
    var direct_extension_edge_count: Int
    var quotiented_collision_pair_count: Int
    var residual_collision_pair_count: Int
    var first_residual_left: Int
    var first_residual_right: Int
    var residue_modulus: Int
    var residue_surviving_residual_pair_count: Int
    var residue_separated_residual_pair_count: Int
    var first_residue_surviving_left: Int
    var first_residue_surviving_right: Int

    def __init__(
        out self,
        sample_count: Int,
        projection_collision_pair_count: Int,
        direct_extension_edge_count: Int,
        quotiented_collision_pair_count: Int,
        residual_collision_pair_count: Int,
        first_residual_left: Int,
        first_residual_right: Int,
        residue_modulus: Int,
        residue_surviving_residual_pair_count: Int,
        residue_separated_residual_pair_count: Int,
        first_residue_surviving_left: Int,
        first_residue_surviving_right: Int,
    ):
        self.sample_count = sample_count
        self.projection_collision_pair_count = projection_collision_pair_count
        self.direct_extension_edge_count = direct_extension_edge_count
        self.quotiented_collision_pair_count = quotiented_collision_pair_count
        self.residual_collision_pair_count = residual_collision_pair_count
        self.first_residual_left = first_residual_left
        self.first_residual_right = first_residual_right
        self.residue_modulus = residue_modulus
        self.residue_surviving_residual_pair_count = (
            residue_surviving_residual_pair_count
        )
        self.residue_separated_residual_pair_count = (
            residue_separated_residual_pair_count
        )
        self.first_residue_surviving_left = first_residue_surviving_left
        self.first_residue_surviving_right = first_residue_surviving_right

    def has_residual_collision(self) -> Bool:
        return self.residual_collision_pair_count > 0

    def has_residue_survivor(self) -> Bool:
        return self.residue_surviving_residual_pair_count > 0


def _validate_projection_bounds(source_radius: Int, digit_window: Int) raises:
    if source_radius < 0 or digit_window < 0:
        raise Error("loop-quotient census radius and digit window must be nonnegative")


def append_addressed_samples_at_depth(
    mut out: List[AddressedJointLocalSample],
    sigma: List[List[Int]],
    pair: Pair,
    specimen_id: Int,
    depth: Int,
    source_radius: Int,
    digit_window: Int,
) raises:
    """Append every certified zero return with one shared certification pass."""
    if depth <= 0:
        raise Error("loop-quotient sample depth must be positive")
    _validate_projection_bounds(source_radius, digit_window)

    var tables = build_renewal_address_tables(sigma, depth)
    var state = build_renewal_pair_census_state(tables, pair)
    var cuts = zero_return_cuts(sigma, pair, depth)
    for i in range(len(cuts)):
        var cut = cuts[i]
        var certified = certified_renewal_cut_from_state(state, cut)
        var projection = joint_local_type_from_certified(
            state, certified, source_radius, digit_window
        )
        out.append(
            AddressedJointLocalSample(
                specimen_id,
                depth,
                cut,
                projection,
                certified.address,
            )
        )


def addressed_samples_through_depth(
    sigma: List[List[Int]],
    pair: Pair,
    specimen_id: Int,
    max_depth: Int,
    source_radius: Int,
    digit_window: Int,
) raises -> List[AddressedJointLocalSample]:
    if max_depth <= 0:
        raise Error("loop-quotient census max_depth must be positive")
    _validate_projection_bounds(source_radius, digit_window)

    var out = List[AddressedJointLocalSample]()
    for depth in range(1, max_depth + 1):
        append_addressed_samples_at_depth(
            out,
            sigma,
            pair,
            specimen_id,
            depth,
            source_radius,
            digit_window,
        )
    return out^


def _rotate_hash(x: UInt64) -> UInt64:
    return (x << 7) | (x >> 57)


def _mix_hash(state: UInt64, value: UInt64) -> UInt64:
    return _rotate_hash(state) ^ value


def _projection_fingerprint(projection: JointLocalType) -> UInt64:
    var h = hash(projection.source_radius)
    h = _mix_hash(h, hash(projection.digit_window))
    h = _mix_hash(h, hash(projection.source_index_delta))
    h = _mix_hash(h, hash(projection.source_defect.x))
    h = _mix_hash(h, hash(projection.source_defect.y))
    h = _mix_hash(h, hash(projection.source_defect.z))
    h = _mix_hash(h, hash(projection.top_source_letter))
    h = _mix_hash(h, hash(projection.bottom_source_letter))
    h = _mix_hash(h, hash(projection.source_context))
    h = _mix_hash(h, hash(projection.top_head))
    h = _mix_hash(h, hash(projection.top_tail))
    h = _mix_hash(h, hash(projection.bottom_head))
    h = _mix_hash(h, hash(projection.bottom_tail))
    return h


def synchronous_any_digit_pair_insertion(
    top_shorter: List[Int],
    top_longer: List[Int],
    bottom_shorter: List[Int],
    bottom_longer: List[Int],
) -> Bool:
    """Detect one synchronous ancestry-level insertion with arbitrary side digits."""
    if len(top_shorter) != len(bottom_shorter):
        return False
    if len(top_longer) != len(bottom_longer):
        return False
    if len(top_shorter) % 2 != 0 or len(top_longer) != len(top_shorter) + 2:
        return False

    for pair_position in range(len(top_shorter) // 2 + 1):
        var pos = 2 * pair_position
        var top_parent = top_longer[pos]
        var top_child_index = top_longer[pos + 1]
        var bottom_parent = bottom_longer[pos]
        var bottom_child_index = bottom_longer[pos + 1]
        if (
            digit_pair_insertion_at(
                top_shorter,
                top_longer,
                top_parent,
                top_child_index,
                pair_position,
            )
            and digit_pair_insertion_at(
                bottom_shorter,
                bottom_longer,
                bottom_parent,
                bottom_child_index,
                pair_position,
            )
        ):
            return True
    return False


def address_is_one_synchronous_extension(
    shorter: RelativeRenewalAddress,
    longer: RelativeRenewalAddress,
) -> Bool:
    """One exact shared-level symbolic extension, allowing different side digits."""
    return (
        longer.level == shorter.level + 1
        and longer.source_index_delta == shorter.source_index_delta
        and longer.source_defect == shorter.source_defect
        and longer.top_source_letter == shorter.top_source_letter
        and longer.bottom_source_letter == shorter.bottom_source_letter
        and synchronous_any_digit_pair_insertion(
            shorter.top_digits,
            longer.top_digits,
            shorter.bottom_digits,
            longer.bottom_digits,
        )
    )


def _related(
    a: AddressedJointLocalSample,
    b: AddressedJointLocalSample,
    relation_mode: Int,
    parent_letter: Int,
    child_index: Int,
) -> Bool:
    if a.address.level + 1 == b.address.level:
        if relation_mode == 0:
            return address_is_one_loop_extension(
                a.address, b.address, parent_letter, child_index
            )
        return address_is_one_synchronous_extension(a.address, b.address)
    if b.address.level + 1 == a.address.level:
        if relation_mode == 0:
            return address_is_one_loop_extension(
                b.address, a.address, parent_letter, child_index
            )
        return address_is_one_synchronous_extension(b.address, a.address)
    return False


def _find_root(parent: List[Int], x: Int) -> Int:
    var root = x
    while parent[root] != root:
        root = parent[root]
    return root


def _union(mut parent: List[Int], a: Int, b: Int):
    var ra = _find_root(parent, a)
    var rb = _find_root(parent, b)
    if ra != rb:
        parent[rb] = ra


def _canonical_mod(x: Int, modulus: Int) -> Int:
    var r = x % modulus
    if r < 0:
        r += modulus
    return r


def _same_scaled_defect_residue(
    a: RelativeRenewalAddress,
    b: RelativeRenewalAddress,
    modulus: Int,
) -> Bool:
    return (
        _canonical_mod(a.scaled_defect.x, modulus)
        == _canonical_mod(b.scaled_defect.x, modulus)
        and _canonical_mod(a.scaled_defect.y, modulus)
        == _canonical_mod(b.scaled_defect.y, modulus)
        and _canonical_mod(a.scaled_defect.z, modulus)
        == _canonical_mod(b.scaled_defect.z, modulus)
    )


def _audit_projection_with_relation(
    samples: List[AddressedJointLocalSample],
    relation_mode: Int,
    parent_letter: Int,
    child_index: Int,
    residue_modulus: Int,
) raises -> LoopQuotientAudit:
    if len(samples) == 0:
        return LoopQuotientAudit(0, 0, 0, 0, 0, -1, -1, residue_modulus, 0, 0, -1, -1)
    if relation_mode < 0 or relation_mode > 1:
        raise Error("unknown loop-quotient relation mode")
    if residue_modulus == 1 or residue_modulus < 0:
        raise Error("residue modulus must be zero (disabled) or at least two")

    var source_radius = samples[0].projection.source_radius
    var digit_window = samples[0].projection.digit_window
    for i in range(1, len(samples)):
        if (
            samples[i].projection.source_radius != source_radius
            or samples[i].projection.digit_window != digit_window
        ):
            raise Error("loop-quotient audit cannot mix projection bounds")

    var seen = Dict[ObservationKey, Int](capacity=len(samples))
    var unique = List[Int]()
    for i in range(len(samples)):
        var key = ObservationKey(
            samples[i].specimen_id, samples[i].depth, samples[i].cut
        )
        if key in seen:
            var prior = seen[key]
            if (
                not same_joint_local_type(
                    samples[i].projection, samples[prior].projection
                )
                or not same_relative_address(samples[i].address, samples[prior].address)
            ):
                raise Error(
                    "duplicate loop-quotient observation identity has conflicting evidence"
                )
            continue
        seen[key.copy()] = i
        unique.append(i)

    var next_member = List[Int]()
    var parent = List[Int]()
    for i in range(len(samples)):
        next_member.append(-1)
        parent.append(i)

    var heads = Dict[UInt64, Int](capacity=len(unique))
    var group_representatives = List[Int]()
    var group_counts = List[Int]()
    var next_group = List[Int]()
    var group_member_head = List[Int]()
    var projection_collisions = 0

    for q in range(len(unique)):
        var i = unique[q]
        var fingerprint = _projection_fingerprint(samples[i].projection)
        var group = -1
        if fingerprint in heads:
            group = heads[fingerprint]

        var matched_group = -1
        while group >= 0:
            if same_joint_local_type(
                samples[i].projection,
                samples[group_representatives[group]].projection,
            ):
                matched_group = group
                break
            group = next_group[group]

        if matched_group < 0:
            matched_group = len(group_representatives)
            group_representatives.append(i)
            group_counts.append(0)
            group_member_head.append(-1)
            if fingerprint in heads:
                next_group.append(heads[fingerprint])
            else:
                next_group.append(-1)
            heads[fingerprint] = matched_group

        projection_collisions += group_counts[matched_group]
        group_counts[matched_group] += 1
        next_member[i] = group_member_head[matched_group]
        group_member_head[matched_group] = i

    var direct_edges = 0
    for g in range(len(group_representatives)):
        if group_counts[g] < 2:
            continue
        var left = group_member_head[g]
        while left >= 0:
            var right = next_member[left]
            while right >= 0:
                if _related(
                    samples[left],
                    samples[right],
                    relation_mode,
                    parent_letter,
                    child_index,
                ):
                    direct_edges += 1
                    _union(parent, left, right)
                right = next_member[right]
            left = next_member[left]

    var quotiented_pairs = 0
    var residual_pairs = 0
    var first_residual_left = -1
    var first_residual_right = -1
    var residue_survivors = 0
    var residue_separated = 0
    var first_residue_surviving_left = -1
    var first_residue_surviving_right = -1

    for g in range(len(group_representatives)):
        if group_counts[g] < 2:
            continue
        var left = group_member_head[g]
        while left >= 0:
            var right = next_member[left]
            while right >= 0:
                if _find_root(parent, left) == _find_root(parent, right):
                    quotiented_pairs += 1
                else:
                    residual_pairs += 1
                    if first_residual_left < 0:
                        first_residual_left = left
                        first_residual_right = right
                    if residue_modulus > 0:
                        if _same_scaled_defect_residue(
                            samples[left].address,
                            samples[right].address,
                            residue_modulus,
                        ):
                            residue_survivors += 1
                            if first_residue_surviving_left < 0:
                                first_residue_surviving_left = left
                                first_residue_surviving_right = right
                        else:
                            residue_separated += 1
                right = next_member[right]
            left = next_member[left]

    if quotiented_pairs + residual_pairs != projection_collisions:
        raise Error("loop-quotient collision accounting failed")
    if residue_modulus > 0 and residue_survivors + residue_separated != residual_pairs:
        raise Error("residue-refinement residual accounting failed")

    return LoopQuotientAudit(
        len(unique),
        projection_collisions,
        direct_edges,
        quotiented_pairs,
        residual_pairs,
        first_residual_left,
        first_residual_right,
        residue_modulus,
        residue_survivors,
        residue_separated,
        first_residue_surviving_left,
        first_residue_surviving_right,
    )


def audit_projection_modulo_loop(
    samples: List[AddressedJointLocalSample],
    parent_letter: Int,
    child_index: Int,
) raises -> LoopQuotientAudit:
    """Quotient collision classes by one nominated same-digit loop family."""
    return _audit_projection_with_relation(samples, 0, parent_letter, child_index, 0)


def audit_projection_modulo_synchronous_extensions(
    samples: List[AddressedJointLocalSample],
) raises -> LoopQuotientAudit:
    """Quotient by all observed shared-level one-pair symbolic extensions."""
    return _audit_projection_with_relation(samples, 1, 0, 0, 0)


def audit_synchronous_residual_scaled_defect_residue(
    samples: List[AddressedJointLocalSample],
    modulus: Int,
) raises -> LoopQuotientAudit:
    """Probe `M^d delta mod modulus` only on residual symbolic collisions.

    The symbolic connected components are formed first. The residue then only
    measures which unresolved pairs a finite arithmetic coordinate would
    separate; it does not itself generate recurrence identifications.
    """
    return _audit_projection_with_relation(samples, 1, 0, 0, modulus)
