"""Finite exact quotient diagnostics for regular joint-local collision loops.

This module does not assert renewal finiteness. It takes the bounded
`JointLocalType` collision classes from the G1b-2 census, retains the full exact
renewal address for each certified observation, and quotients only by the
connected components generated by a nominated synchronous one-level loop
extension.

The quotient is deliberately empirical and corpus-relative. It does not delete
all occurrences of a digit pair from an address and does not invent a global
normal form. Two colliding observations are identified only when the observed
collision graph connects them by exact certified loop-extension edges. Pairs in
different components remain explicit residual counterexamples.
"""

from psc.joint_local_census import ObservationKey, address_is_one_loop_extension, zero_return_cuts
from psc.joint_local_type import (
    JointLocalType,
    joint_local_type_from_certified,
    same_joint_local_type,
)
from psc.renewal_address import (
    RelativeRenewalAddress,
    build_renewal_address_tables,
    build_renewal_pair_census_state,
    certified_renewal_cut_from_state,
    same_relative_address,
)
from psc.words import Pair


struct AddressedJointLocalSample(Copyable, Movable):
    """One certified bounded projection together with its exact full address."""

    var specimen_id: Int
    var depth: Int
    var cut: Int
    var projection: JointLocalType
    var address: RelativeRenewalAddress

    def __init__(
        out self,
        specimen_id: Int,
        depth: Int,
        cut: Int,
        projection: JointLocalType,
        address: RelativeRenewalAddress,
    ):
        self.specimen_id = specimen_id
        self.depth = depth
        self.cut = cut
        self.projection = projection.copy()
        self.address = address.copy()


struct LoopQuotientAudit(Copyable, Movable):
    """Collision counts before and after the observed regular-loop quotient."""

    var sample_count: Int
    var projection_collision_pair_count: Int
    var direct_loop_edge_count: Int
    var quotiented_collision_pair_count: Int
    var residual_collision_pair_count: Int
    var first_residual_left: Int
    var first_residual_right: Int

    def __init__(
        out self,
        sample_count: Int,
        projection_collision_pair_count: Int,
        direct_loop_edge_count: Int,
        quotiented_collision_pair_count: Int,
        residual_collision_pair_count: Int,
        first_residual_left: Int,
        first_residual_right: Int,
    ):
        self.sample_count = sample_count
        self.projection_collision_pair_count = projection_collision_pair_count
        self.direct_loop_edge_count = direct_loop_edge_count
        self.quotiented_collision_pair_count = quotiented_collision_pair_count
        self.residual_collision_pair_count = residual_collision_pair_count
        self.first_residual_left = first_residual_left
        self.first_residual_right = first_residual_right

    def has_residual_collision(self) -> Bool:
        return self.residual_collision_pair_count > 0


def _validate_projection_bounds(source_radius: Int, digit_window: Int) raises:
    if source_radius < 0 or digit_window < 0:
        raise Error("loop-quotient census radius and digit window must be nonnegative")


def append_addressed_samples_at_depth(
    mut out: List[AddressedJointLocalSample],
    sigma: List[List[Int]],
    pair: Pair,
    specimen_id: Int,
    depth: Int,
    source_radius: Int,
    digit_window: Int,
) raises:
    """Append every certified zero return with one shared certification pass."""
    if depth <= 0:
        raise Error("loop-quotient sample depth must be positive")
    _validate_projection_bounds(source_radius, digit_window)

    var tables = build_renewal_address_tables(sigma, depth)
    var state = build_renewal_pair_census_state(tables, pair)
    var cuts = zero_return_cuts(sigma, pair, depth)
    for i in range(len(cuts)):
        var cut = cuts[i]
        var certified = certified_renewal_cut_from_state(state, cut)
        var projection = joint_local_type_from_certified(
            state, certified, source_radius, digit_window
        )
        out.append(
            AddressedJointLocalSample(
                specimen_id,
                depth,
                cut,
                projection,
                certified.address,
            )
        )


def addressed_samples_through_depth(
    sigma: List[List[Int]],
    pair: Pair,
    specimen_id: Int,
    max_depth: Int,
    source_radius: Int,
    digit_window: Int,
) raises -> List[AddressedJointLocalSample]:
    if max_depth <= 0:
        raise Error("loop-quotient census max_depth must be positive")
    _validate_projection_bounds(source_radius, digit_window)

    var out = List[AddressedJointLocalSample]()
    for depth in range(1, max_depth + 1):
        append_addressed_samples_at_depth(
            out,
            sigma,
            pair,
            specimen_id,
            depth,
            source_radius,
            digit_window,
        )
    return out^


def _rotate_hash(x: UInt64) -> UInt64:
    return (x << 7) | (x >> 57)


def _mix_hash(state: UInt64, value: UInt64) -> UInt64:
    return _rotate_hash(state) ^ value


def _projection_fingerprint(projection: JointLocalType) -> UInt64:
    var h = hash(projection.source_radius)
    h = _mix_hash(h, hash(projection.digit_window))
    h = _mix_hash(h, hash(projection.source_index_delta))
    h = _mix_hash(h, hash(projection.source_defect.x))
    h = _mix_hash(h, hash(projection.source_defect.y))
    h = _mix_hash(h, hash(projection.source_defect.z))
    h = _mix_hash(h, hash(projection.top_source_letter))
    h = _mix_hash(h, hash(projection.bottom_source_letter))
    h = _mix_hash(h, hash(projection.source_context))
    h = _mix_hash(h, hash(projection.top_head))
    h = _mix_hash(h, hash(projection.top_tail))
    h = _mix_hash(h, hash(projection.bottom_head))
    h = _mix_hash(h, hash(projection.bottom_tail))
    return h


def _loop_related(
    a: AddressedJointLocalSample,
    b: AddressedJointLocalSample,
    parent_letter: Int,
    child_index: Int,
) -> Bool:
    if a.address.level + 1 == b.address.level:
        return address_is_one_loop_extension(
            a.address, b.address, parent_letter, child_index
        )
    if b.address.level + 1 == a.address.level:
        return address_is_one_loop_extension(
            b.address, a.address, parent_letter, child_index
        )
    return False


def _find_root(parent: List[Int], x: Int) -> Int:
    var root = x
    while parent[root] != root:
        root = parent[root]
    return root


def _union(mut parent: List[Int], a: Int, b: Int):
    var ra = _find_root(parent, a)
    var rb = _find_root(parent, b)
    if ra != rb:
        parent[rb] = ra


def audit_projection_modulo_loop(
    samples: List[AddressedJointLocalSample],
    parent_letter: Int,
    child_index: Int,
) raises -> LoopQuotientAudit:
    """Quotient exact projection collisions by observed loop-connected classes.

    Projection classes are interned in near-linear expected time. Pairwise loop
    tests are performed only inside classes that actually collide, so the
    secondary quotient work scales with the number of projection-collision
    pairs rather than with the square of the entire corpus.

    Exact duplicate observation identities are deduplicated only after both the
    bounded projection and full renewal address agree. Mixed projection bounds
    fail closed because they are incomparable evidence.
    """
    if len(samples) == 0:
        return LoopQuotientAudit(0, 0, 0, 0, 0, -1, -1)

    var source_radius = samples[0].projection.source_radius
    var digit_window = samples[0].projection.digit_window
    for i in range(1, len(samples)):
        if (
            samples[i].projection.source_radius != source_radius
            or samples[i].projection.digit_window != digit_window
        ):
            raise Error("loop-quotient audit cannot mix projection bounds")

    var seen = Dict[ObservationKey, Int](capacity=len(samples))
    var unique = List[Int]()
    for i in range(len(samples)):
        var key = ObservationKey(
            samples[i].specimen_id, samples[i].depth, samples[i].cut
        )
        if key in seen:
            var prior = seen[key]
            if (
                not same_joint_local_type(
                    samples[i].projection, samples[prior].projection
                )
                or not same_relative_address(samples[i].address, samples[prior].address)
            ):
                raise Error(
                    "duplicate loop-quotient observation identity has conflicting evidence"
                )
            continue
        seen[key.copy()] = i
        unique.append(i)

    var next_member = List[Int]()
    var group_of = List[Int]()
    var parent = List[Int]()
    for i in range(len(samples)):
        next_member.append(-1)
        group_of.append(-1)
        parent.append(i)

    var heads = Dict[UInt64, Int](capacity=len(unique))
    var group_representatives = List[Int]()
    var group_counts = List[Int]()
    var next_group = List[Int]()
    var group_member_head = List[Int]()
    var projection_collisions = 0

    for q in range(len(unique)):
        var i = unique[q]
        var fingerprint = _projection_fingerprint(samples[i].projection)
        var group = -1
        if fingerprint in heads:
            group = heads[fingerprint]

        var matched_group = -1
        while group >= 0:
            if same_joint_local_type(
                samples[i].projection,
                samples[group_representatives[group]].projection,
            ):
                matched_group = group
                break
            group = next_group[group]

        if matched_group < 0:
            matched_group = len(group_representatives)
            group_representatives.append(i)
            group_counts.append(0)
            group_member_head.append(-1)
            if fingerprint in heads:
                next_group.append(heads[fingerprint])
            else:
                next_group.append(-1)
            heads[fingerprint] = matched_group

        projection_collisions += group_counts[matched_group]
        group_counts[matched_group] += 1
        group_of[i] = matched_group
        next_member[i] = group_member_head[matched_group]
        group_member_head[matched_group] = i

    var direct_loop_edges = 0
    for g in range(len(group_representatives)):
        if group_counts[g] < 2:
            continue
        var left = group_member_head[g]
        while left >= 0:
            var right = next_member[left]
            while right >= 0:
                if _loop_related(
                    samples[left], samples[right], parent_letter, child_index
                ):
                    direct_loop_edges += 1
                    _union(parent, left, right)
                right = next_member[right]
            left = next_member[left]

    var quotiented_pairs = 0
    var residual_pairs = 0
    var first_residual_left = -1
    var first_residual_right = -1
    for g in range(len(group_representatives)):
        if group_counts[g] < 2:
            continue
        var left = group_member_head[g]
        while left >= 0:
            var right = next_member[left]
            while right >= 0:
                if _find_root(parent, left) == _find_root(parent, right):
                    quotiented_pairs += 1
                else:
                    residual_pairs += 1
                    if first_residual_left < 0:
                        first_residual_left = left
                        first_residual_right = right
                right = next_member[right]
            left = next_member[left]

    if quotiented_pairs + residual_pairs != projection_collisions:
        raise Error("loop-quotient collision accounting failed")

    return LoopQuotientAudit(
        len(unique),
        projection_collisions,
        direct_loop_edges,
        quotiented_pairs,
        residual_pairs,
        first_residual_left,
        first_residual_right,
    )
